# Generated by Django 6.0 on 2025-12-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('language', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='books')),
            ],
        ),
    ]
