# Generated by Django 6.0 on 2025-12-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('name', models.CharField()),
                ('deptname', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('designation', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='employeeimg')),
            ],
        ),
    ]
